# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(894, 993)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(894, 993))
        mainWindow.setMaximumSize(QtCore.QSize(894, 993))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Catalog = QtWidgets.QComboBox(self.centralwidget)
        self.Catalog.setGeometry(QtCore.QRect(20, 10, 291, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Catalog.sizePolicy().hasHeightForWidth())
        self.Catalog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Catalog.setFont(font)
        self.Catalog.setObjectName("Catalog")
        self.Catalog.addItem("")
        self.Catalog.setItemText(0, "")
        self.Catalog.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(740, 930, 141, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftArrow = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.leftArrow.setObjectName("leftArrow")
        self.horizontalLayout.addWidget(self.leftArrow)
        self.currentPage = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.currentPage.setFont(font)
        self.currentPage.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPage.setObjectName("currentPage")
        self.horizontalLayout.addWidget(self.currentPage)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.maxPages = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.maxPages.setFont(font)
        self.maxPages.setAlignment(QtCore.Qt.AlignCenter)
        self.maxPages.setObjectName("maxPages")
        self.horizontalLayout.addWidget(self.maxPages)
        self.rightArrow = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rightArrow.setObjectName("rightArrow")
        self.horizontalLayout.addWidget(self.rightArrow)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(750, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.CategoryName = QtWidgets.QLabel(self.centralwidget)
        self.CategoryName.setGeometry(QtCore.QRect(320, 10, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CategoryName.setFont(font)
        self.CategoryName.setText("")
        self.CategoryName.setAlignment(QtCore.Qt.AlignCenter)
        self.CategoryName.setObjectName("CategoryName")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 60, 861, 861))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Епіцентр"))
        self.Catalog.setItemText(1, _translate("mainWindow", "Каталог"))
        self.leftArrow.setText(_translate("mainWindow", "<-"))
        self.currentPage.setText(_translate("mainWindow", "0"))
        self.label_5.setText(_translate("mainWindow", "із"))
        self.maxPages.setText(_translate("mainWindow", "1"))
        self.rightArrow.setText(_translate("mainWindow", "->"))
        self.backButton.setText(_translate("mainWindow", "Повернутись"))
